name = "MerCounting"
uuid = "a20136b7-8e32-4c10-91d3-7060c0bd8ec7"
authors = ["Ben J. Ward <benjward@protonmail.com>"]
version = "0.1.0"

[deps]
ReadDatastores = "70a005b8-9d8a-11e9-0d98-c909fa2e52d2"

[compat]
ReadDatastores = "0.2.1"